# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messageForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from logic import send_message, read_template

class MessageDialog(object):
    def __init__(self, login, password, server):
        self.login = login
        self.password = password
        self.server = server

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(668, 492)
        Dialog.setMinimumSize(QtCore.QSize(491, 0))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 40, 631, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(20, 80, 631, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.label_4.setObjectName("label_4")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(20, 120, 631, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 55, 16))
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(560, 450, 93, 28))

        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextBrowser(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(90, 10, 491, 31))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 10, 61, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.get_contacts_file)
        self.textBrowser = QtWidgets.QTextEdit(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(90, 50, 491, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setText(self.login)
        self.textBrowser_2 = QtWidgets.QTextEdit(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(90, 90, 491, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 140, 631, 281))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(20, 440, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 440, 155, 16))
        self.label_5.setObjectName("label_5")
        self.retranslateUi(Dialog)
        self.set_template_browser()
        self.comboBox.currentTextChanged.connect(self.set_template_browser)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.send)

    def send(self):
        self.label_5.setText(send_message(self.comboBox.currentText() + '.txt', self.server,
                     self.login, self.password, self.textBrowser.toPlainText(),
                     self.textBrowser_2.toPlainText(), self.textEdit.toPlainText()))

    def get_subject(self):
        return self.textBrowser1.toPlainText()

    def set_template_browser(self):
        self.textBrowser_3.setText(read_template(str(self.comboBox.currentText()) +
                                                 '.txt').substitute(PERSON_NAME='Person'))

    def get_contacts_file(self):
        filename = QtWidgets.QFileDialog.getOpenFileName(
            None, 'Get contacts from file', '', 'Only txt files allowed (*.txt)')[0]
        self.textEdit.setText(filename)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "To"))
        self.label_3.setText(_translate("Dialog", "From"))
        self.label_4.setText(_translate("Dialog", "From"))
        self.label_6.setText(_translate("Dialog", "Subject"))
        self.pushButton.setText(_translate("Dialog", "Send"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog", "Browse"))
        self.comboBox.setItemText(0, _translate("Dialog", "Weekend greeting"))
        self.comboBox.setItemText(1, _translate("Dialog", "Thanks for feedback"))
        self.label_5.setText(_translate("Dialog", "fill the fields"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = MessageDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
