# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from loginWindow import Ui_Dialog as LoginForm

class Ui_Dialog(object):
    def openWindow(self):
        self.window = QtWidgets.QDialog()
        self.message = self.comboBox.currentText()
        self.ui = LoginForm(self.message)
        self.ui.setupUi(self.window)
        Dialog.hide()
        self.window.show()

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 109)
        Dialog.setMinimumSize(QtCore.QSize(450, 109))
        self.serverlabel = QtWidgets.QLabel(Dialog)
        self.serverlabel.setGeometry(QtCore.QRect(100, 40, 121, 21))
        self.serverlabel.setMinimumSize(QtCore.QSize(121, 21))
        self.serverlabel.setObjectName("serverlabel")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(240, 40, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.next = QtWidgets.QPushButton(Dialog)
        self.next.setGeometry(QtCore.QRect(422, 70, 61, 28))
        self.next.setObjectName("next")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.next.clicked.connect(self.openWindow)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.serverlabel.setText(_translate("Dialog", "Choose e-mail client:"))
        self.comboBox.setItemText(0, _translate("Dialog", "gmail"))
        self.comboBox.setItemText(1, _translate("Dialog", "mail.ru"))
        self.comboBox.setItemText(2, _translate("Dialog", "yandex"))
        self.comboBox.setItemText(3, _translate("Dialog", "yahoo"))
        self.comboBox.setItemText(4, _translate("Dialog", "outlook"))
        self.next.setText(_translate("Dialog", ">"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
